### PR TITLE
allocate local port dynamically, fixes #290

### LINKED ISSUE #290: Dynamic port on localhost
For testing purposes and embedding ledisdb in other applications, having a free localhost port dynamically allocated would be very handy. This would be similar to https://golang.org/pkg/net/http/httptest/#Server

When looking at the code, they use
```go
                l, err := net.Listen("tcp", "127.0.0.1:0")
		if err != nil {
			if l, err = net.Listen("tcp6", "[::1]:0"); err != nil {
				panic(fmt.Sprintf("httptest: failed to listen on a port: %v", err))
			}
		}
```

So this would have to be added at https://github.com/siddontang/ledisdb/blob/master/server/app.go#L93

In order to grab back the address, an extra property `Address` would have to be added to the App struct and assigned after starting to listen.
 
If you think this would be a good thing, I'm happy to create a PR for this.

### PR DESCRIPTION
**Pull request by GlenDC**
This PR fixes issue #290, as discussed and agreed in the issue itself.

### CODE REVIEW

**Comment by GlenDC** [comment]
Is this PR fine @siddontang, or do you require changes?

**Comment by siddontang** [comment]
Thanks @GlenDC

I still want to use "127.0.0.1:2380" for server by default, but now the default config address is empty, maybe we can set it explicitly after https://github.com/siddontang/ledisdb/blob/master/cmd/ledis-server/main.go#L42.

**Comment by GlenDC** [comment]
Sure it's possible. In our case we're not using the server though, and creating the App directly. Your proposes request does seem reasonable. What is the reason, if I may ask, that you would prefer to keep the server default? As it seems like a pretty randomly chosen port value, anyhow.

**Comment by siddontang** [comment]
Hi @GlenDC

Like redis using 2379 as the default port, I prefer using 2380 for ledisdb server. For a server, using a random port to start may be strange. :-)

**Comment by robvanmieghem** [comment]
I think having a property on the App struct like "UseFreeLocalAddress" would be fine. This way it is not done through the config but explicitly through the App object. One would probably never do this through a non-embedded App anyway since you can not know the port that way.

**Comment by GlenDC** [comment]
@siddontang I guess you mean 6379 and 6380, instead of 2379 and 2380. That does sound reasonable. I changed the only commit of this PR to reflect your request.

@robvanmieghem I think allowing to set the `(*Config).Addr` property to the empty string is a better solution, as it doesn't add yet another property. Adding an extra property that serves to override the given config is a bit confusing, and adds another layer of indirection with no good reason IMHO. I was also thinking to provide a new constructor, but that would again override the existing `(*Config).Addr` property, which I think can be very confusing.

Explicitly passing/assigning empty strings is a common thing to do in the Go STD As well, so therefore I went with the suggested approach of @siddontang.

**Comment by siddontang** [comment]
Aha @GlenDC 

2379 and 2380 are the default port for etcd, I am wrong. :-)

**Comment by siddontang** [comment]
Hi @GlenDC @robvanmieghem 

For another config like "UseFreeLocalAddress", maybe we can use `toml:"-"` to ignore this field explicitly.

I think this change is ok for me now, I will merge it. Thank you.

**Pull request merged**
