### PR TITLE
RESP writer test

### PR DESCRIPTION
**Pull request by nikolay-turpitko**
Unit test for respWriter to be sure that it conforms to http://redis.io/topics/protocol.

### CODE REVIEW

**Comment by siddontang** [comment]
Hi @nikolay-turpitko 

I think either bool or nil is ok, if redis returns bool, we can also return it too. :-) 

Thank you.

**Comment by nikolay-turpitko** [comment]
I removed comments from the script.go and commented unit tests for resp writer. So, if you OK with both, please merge them from one PR, I'd rather not spend a time to split it. Thanks.

**Comment by siddontang** [comment]
Hi @nikolay-turpitko 

I see this PR supports bool, if yes, we can merge this. ok?

**Comment by nikolay-turpitko** [comment]
yep

**Comment by siddontang** [comment]
LGTM 
Thank you @nikolay-turpitko

**Pull request merged**
