### PR TITLE
Custom auth method

### PR DESCRIPTION
**Pull request by muhamadazmy**
The custom auth method is very useful if we need to implement
our own authentication rather than the default simple password matching

- This way we can pass a JWT token as a password, where the auth method
will make sure to validate the token before granting access

### CODE REVIEW

**Comment by muhamadazmy** [comment]
The tests are falling due to a bad `toml` library.
While the `Config.AuthMethod ` is explicitly given the tag `toml:"-"` it still tries to reflect it's type which (of course) not supported by the toml library.

I suggest u move to a better toml library, or suggest a better solution

**Comment by siddontang** [comment]
Thanks @muhamadazmy 

Upgrading the toml libary can solve the problem? If yes, I will upgrade it.

**Comment by muhamadazmy** [comment]
I will try some other libraries and see which will work the best. Thanks a lot for your feedback :)

**Comment by siddontang** [comment]
Thanks @muhamadazmy 

Does the latest https://github.com/BurntSushi/toml fix this problem, if yes, we can upgrade it directly?

**Comment by muhamadazmy** [comment]
@siddontang it passes now. I used https://github.com/pelletier/go-toml instead. I also updated the vendor directory.

By the way, how do you maintain your vendor directory? It's not compatible with `godep` and I had to do it manually.

About your question regarding BurntSushi/toml, It was too late when i saw your comment i already did the migration to go-toml. Sorry.

**Comment by siddontang** [comment]
Hi @muhamadazmy 

Now we use glide to manage the vendor.

You can update this in the glide.yaml (removing origin TOML, add new one)  and run `make update_vendor` which will clean up the imported test file.

**Comment by muhamadazmy** [comment]
Hi @siddontang 
Fixed `vendor` as you said :)

**Comment by siddontang** [comment]
LGTM

Thanks @muhamadazmy

**Pull request merged**
